

type Season {
    season: Int!
    rounds: [Round]!
}

type Round {
    name: String!
    series: [Series]!
}

type Series {
    teamOne: Team!
    teamTwo: Team!
    seriesVictor: Int!
    games: [Game]!
}

type Game {
    teamOne: Team!
    teamTwo: Team!
    teamOneScorers: [Player]!
    teamTwoScorers: [Player]!
    gameVictor: Int!
    venue: String!
    hdHighlights: String!
    sdHighlights: String    # optional
}

type Team {
    teamId: Int!
    teamName: String!
}

type Player {
    playerId: Int!
    playerName: String!
}






type 